import Footer from '@/components/Footer';
import Navigation from '@/components/Navigation';
import { Inter } from 'next/font/google';
import { twJoin } from 'tailwind-merge';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${twJoin("bg-slate-800 max-w-[1800px] mx-auto scroll-smooth overflow-x-hidden")}`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
